In [17]:
import h2o
from h2o.estimators.random_forest import H2ORandomForestEstimator
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.
Warning: Your H2O cluster version is too old (8 months and 14 days)! Please download and install the latest version from http://h2o.ai/download/

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         2 hours 44 mins
H2O_cluster_timezone:       Asia/Kolkata
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.2
H2O_cluster_version_age:    8 months and 14 days !!!
H2O_cluster_name:           H2O_from_python_Shruti_ktdu5w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1000 Mb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.6 final
--------------------------  ---------------------------------------------------------

In [18]:
saved_model = h2o.load_model(model_path)
saved_model

Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_model_python_1642003532924_21


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,50.0,50.0,18761.0,6.0,11.0,8.3,18.0,31.0,25.16

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: 0.05850758174973697
RMSE: 0.24188340527976898
LogLoss: 0.47455265157131143
Mean Per-Class Error: 0.0705922865013775
AUC: 0.9694538972613839
AUCPR: 0.9756886142953175
Gini: 0.9389077945227677

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.4545454545454546:

              0      1   Error           Rate
0      0  107.0   14.0  0.1157   (14.0/121.0)
1      1   10.0  194.0   0.049   (10.0/204.0)
2  Total  117.0  208.0  0.0738   (24.0/325.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value   idx
0                        max f1   0.454545    0.941748  46.0
1                        max f2   0.176471    0.961722  62.0
2                  max f0point5   0.615385    0.954082  36.0
3                  max accuracy   0.615385    0.926154  36.0
4                 max precision   0.947368    0.986395   5.0
5                    max recall   0.000000    1.000000  81.0
6               max specificity   1.000000    0.983471   0.0
7              max absolute_mcc   0.615385    0.846391  36.0
8    max min_per_class_accuracy   0.571429    0.925620  38.0
9   max mean_per_class_accuracy   0.615385    0.929408  36.0
10                      max tns   1.000000  119.000000   0.0
11                      max fns   1.000000   67.000000   0.0
12                      max fps   0.000000  121.000000  81.0
13                      max tps   0.000000  204.000000  81.0
14                      max tnr   1.000000    0.983471   0.0
15                      max fnr   1.000000    0.328431   0.0
16                      max fpr   0.000000    1.000000  81.0
17                      max tpr   0.000000    1.000000  81.0

Gains/Lift Table: Avg response rate: 62.77 %, avg score: 62.29 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.427692,1.000000,1.570214,1.570214,0.985612,1.000000,0.985612,1.000000,0.671569,0.671569,57.021442,57.021442,0.655040
1,2,0.510769,0.888889,1.475127,1.554748,0.925926,0.931652,0.975904,0.988883,0.122549,0.794118,47.512709,55.474841,0.761060
2,3,0.609231,0.567857,1.344210,1.520722,0.843750,0.748361,0.954545,0.950011,0.132353,0.926471,34.420956,52.072193,0.852090
3,4,0.716923,0.142857,0.546218,1.374337,0.342857,0.346447,0.862661,0.859347,0.058824,0.985294,-45.378151,37.433729,0.720831
4,5,1.000000,0.000000,0.051950,1.000000,0.032609,0.023987,0.627692,0.622876,0.014706,1.000000,-94.804987,0.000000,0.000000

ModelMetricsBinomial: drf
** Reported on validation data. **

MSE: 0.07405890410958903
RMSE: 0.2721376565446043
LogLoss: 0.2527782254280723
Mean Per-Class Error: 0.08257918552036192
AUC: 0.9690799396681751
AUCPR: 0.9674642627067458
Gini: 0.9381598793363501

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.62:

             0     1   Error         Rate
0      0  36.0   3.0  0.0769   (3.0/39.0)
1      1   3.0  31.0  0.0882   (3.0/34.0)
2  Total  39.0  34.0  0.0822   (6.0/73.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value   idx
0                        max f1       0.62   0.911765   9.0
1                        max f2       0.33   0.942857  14.0
2                  max f0point5       0.84   0.925926   7.0
3                  max accuracy       0.84   0.917808   7.0
4                 max precision       1.00   1.000000   0.0
5                    max recall       0.02   1.000000  22.0
6               max specificity       1.00   1.000000   0.0
7              max absolute_mcc       0.84   0.835493   7.0
8    max min_per_class_accuracy       0.62   0.911765   9.0
9   max mean_per_class_accuracy       0.62   0.917421   9.0
10                      max tns       1.00  39.000000   0.0
11                      max fns       1.00  13.000000   0.0
12                      max fps       0.00  39.000000  23.0
13                      max tps       0.02  34.000000  22.0
14                      max tnr       1.00   1.000000   0.0
15                      max fnr       1.00   0.382353   0.0
16                      max fpr       0.00   1.000000  23.0
17                      max tpr       0.02   1.000000  22.0

Gains/Lift Table: Avg response rate: 46.58 %, avg score: 49.68 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.287671,1.000,2.147059,2.147059,1.000000,1.000000,1.000000,1.000000,0.617647,0.617647,114.705882,114.705882,0.617647
1,2,0.342466,0.980,1.610294,2.061176,0.750000,0.980000,0.960000,0.996800,0.088235,0.705882,61.029412,106.117647,0.680241
2,3,0.424658,0.860,1.789216,2.008539,0.833333,0.891667,0.935484,0.976452,0.147059,0.852941,78.921569,100.853890,0.801659
3,4,0.520548,0.385,0.920168,1.808050,0.428571,0.622857,0.842105,0.911316,0.088235,0.941176,-7.983193,80.804954,0.787330
4,5,0.630137,0.050,0.268382,1.540281,0.125000,0.190000,0.717391,0.785870,0.029412,0.970588,-73.161765,54.028133,0.637255
5,6,1.000000,0.000,0.079521,1.000000,0.037037,0.004444,0.465753,0.496849,0.029412,1.000000,-92.047930,0.000000,0.000000

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error,validation_rmse,validation_logloss,validation_auc,validation_pr_auc,validation_lift,validation_classification_error
0,,2022-01-13 00:10:26,0.000 sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,,2022-01-13 00:10:26,0.093 sec,1.0,0.293610,2.977481,0.909697,0.899545,1.452566,0.086207,0.370117,4.731339,0.862368,0.817359,1.831315,0.136986
2,,2022-01-13 00:10:26,0.109 sec,2.0,0.284682,2.668254,0.916300,0.916371,1.477273,0.082418,0.325829,2.905270,0.907240,0.837299,1.811581,0.095890
3,,2022-01-13 00:10:26,0.141 sec,3.0,0.276651,2.366327,0.927131,0.936480,1.512907,0.084746,0.308431,2.006104,0.925716,0.879220,1.924949,0.109589
4,,2022-01-13 00:10:26,0.173 sec,4.0,0.260257,2.058279,0.934559,0.940286,1.514464,0.069853,0.291870,1.992574,0.929487,0.882235,1.917017,0.082192
5,,2022-01-13 00:10:26,0.197 sec,5.0,0.259638,1.924205,0.937303,0.943539,1.519038,0.071672,0.291195,1.993234,0.930241,0.883141,1.917017,0.068493
6,,2022-01-13 00:10:26,0.228 sec,6.0,0.252256,1.646182,0.943224,0.947137,1.521536,0.072607,0.285194,1.545174,0.939291,0.907538,1.988017,0.082192
7,,2022-01-13 00:10:26,0.244 sec,7.0,0.247208,1.409066,0.951157,0.957079,1.539133,0.071429,0.285592,1.547177,0.938914,0.907352,1.988017,0.082192
8,,2022-01-13 00:10:26,0.275 sec,8.0,0.255891,1.397535,0.950562,0.960766,1.548386,0.076433,0.292145,1.556084,0.937406,0.905994,1.988017,0.095890
9,,2022-01-13 00:10:26,0.306 sec,9.0,0.249152,1.172442,0.955640,0.962680,1.548636,0.081761,0.286322,1.112942,0.947587,0.933058,2.064480,0.095890
10,,2022-01-13 00:10:26,0.338 sec,10.0,0.247210,1.161798,0.955841,0.963261,1.549128,0.080997,0.283508,1.109738,0.948341,0.933657,2.064480,0.082192
11,,2022-01-13 00:10:27,0.353 sec,11.0,0.249510,1.155561,0.957128,0.967037,1.557734,0.083333,0.280049,0.672446,0.958145,0.962768,2.147059,0.082192
12,,2022-01-13 00:10:27,0.385 sec,12.0,0.247800,1.056568,0.958517,0.967129,1.556723,0.080247,0.278058,0.672106,0.957768,0.961855,2.147059,0.082192
13,,2022-01-13 00:10:27,0.416 sec,13.0,0.245801,1.052218,0.959144,0.967281,1.556513,0.076923,0.280943,0.677549,0.957014,0.961159,2.147059,0.082192
14,,2022-01-13 00:10:27,0.431 sec,14.0,0.240717,0.949220,0.961919,0.968157,1.555871,0.061538,0.283597,0.684468,0.954374,0.957788,2.147059,0.082192
15,,2022-01-13 00:10:27,0.463 sec,15.0,0.237598,0.946566,0.962587,0.968460,1.555652,0.058462,0.286027,0.689349,0.954374,0.957788,2.147059,0.082192
16,,2022-01-13 00:10:27,0.478 sec,16.0,0.240351,0.950477,0.962121,0.968180,1.555430,0.061538,0.285827,0.691803,0.955128,0.958513,2.147059,0.082192
17,,2022-01-13 00:10:27,0.510 sec,17.0,0.246027,0.858040,0.962000,0.967547,1.554978,0.073846,0.285677,0.687389,0.956637,0.960434,2.147059,0.082192
18,,2022-01-13 00:10:27,0.541 sec,18.0,0.248998,0.862710,0.960501,0.966435,1.554042,0.080000,0.286082,0.689509,0.956259,0.960065,2.147059,0.082192
19,,2022-01-13 00:10:27,0.572 sec,19.0,0.250130,0.864796,0.959934,0.966052,1.553801,0.080000,0.284682,0.688536,0.957014,0.960450,2.147059,0.082192

See the whole table with table.as_data_frame()

Variable Importances:

       variable  relative_importance  scaled_importance  percentage
0  displacement          1282.410889           1.000000    0.412768
1        weight           796.996216           0.621483    0.256528
2         power           597.202148           0.465687    0.192221
3  acceleration           225.565918           0.175892    0.072603
4          year           204.677505           0.159604    0.065879

In [41]:
cars1 = h2o.import_file(path="E:\\DataScience\\cars_20mpgCopy.csv")

cars1

Parse progress: |█████████████████████████████████████████████████████████| 100%

name,economy,cylinders,displacement,power,weight,acceleration,year,economy_20mpg
AMC Ambassador Brougham,13,8,360,175,3821,11,73,0
AMC Ambassador DPL,15,8,390,190,3850,8.5,70,0
AMC Ambassador SST,17,8,304,150,3672,11.5,72,0
AMC Concord DL 6,20.2,6,232,90,3265,18.2,79,1
AMC Concord DL,18.1,6,258,120,3410,15.1,78,0
AMC Concord DL,23,4,151,nan,3035,20.5,82,1
AMC Concord,19.4,6,232,90,3210,17.2,78,0
AMC Concord,24.3,4,151,90,3003,20.1,80,1
AMC Gremlin,18,6,232,100,2789,15,73,0
AMC Gremlin,19,6,232,100,2634,13,71,0

In [42]:
perf = saved_model.model_performance(cars1)
perf

ModelMetricsBinomial: drf
** Reported on test data. **

MSE: 0.020402763819095452
RMSE: 0.14283824354526153
LogLoss: 0.08378358653419916
Mean Per-Class Error: 0.01567752100840336
AUC: 0.99515493697479
AUCPR: 0.9967501260591881
Gini: 0.9903098739495799

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.62:

              0      1   Error          Rate
0      0  157.0    3.0  0.0187   (3.0/160.0)
1      1    3.0  235.0  0.0126   (3.0/238.0)
2  Total  160.0  238.0  0.0151   (6.0/398.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value   idx
0                        max f1       0.62    0.987395  22.0
1                        max f2       0.50    0.989103  25.0
2                  max f0point5       0.62    0.987395  22.0
3                  max accuracy       0.62    0.984925  22.0
4                 max precision       1.00    1.000000   0.0
5                    max recall       0.02    1.000000  51.0
6               max specificity       1.00    1.000000   0.0
7              max absolute_mcc       0.62    0.968645  22.0
8    max min_per_class_accuracy       0.64    0.981250  21.0
9   max mean_per_class_accuracy       0.62    0.984322  22.0
10                      max tns       1.00  160.000000   0.0
11                      max fns       1.00   81.000000   0.0
12                      max fps       0.00  160.000000  53.0
13                      max tps       0.02  238.000000  51.0
14                      max tnr       1.00    1.000000   0.0
15                      max fnr       1.00    0.340336   0.0
16                      max fpr       0.00    1.000000  53.0
17                      max tpr       0.02    1.000000  51.0

Gains/Lift Table: Avg response rate: 59.80 %, avg score: 60.38 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.394472,1.000,1.672269,1.672269,1.000000,1.000000,1.000000,1.000000,0.659664,0.659664,67.226891,67.226891,0.659664
1,2,0.454774,0.980,1.602591,1.663030,0.958333,0.980417,0.994475,0.997403,0.096639,0.756303,60.259104,66.302985,0.750053
2,3,0.515075,0.920,1.672269,1.664111,1.000000,0.944167,0.995122,0.991171,0.100840,0.857143,67.226891,66.411150,0.850893
3,4,0.608040,0.470,1.446287,1.630808,0.864865,0.780811,0.975207,0.959008,0.134454,0.991597,44.628662,63.080769,0.954097
4,5,0.706030,0.045,0.042879,1.410419,0.025641,0.188718,0.843416,0.852100,0.004202,0.995798,-95.712131,41.041897,0.720798
5,6,1.000000,0.000,0.014293,1.000000,0.008547,0.007436,0.597990,0.603794,0.004202,1.000000,-98.570710,0.000000,0.000000

In [43]:
ca=cars1['name'].cbind(sa)
ca

name,predict,p0,p1
AMC Ambassador Brougham,0,1,0
AMC Ambassador DPL,0,1,0
AMC Ambassador SST,0,0.98,0.02
AMC Concord DL 6,0,0.67,0.33
AMC Concord DL,0,0.86,0.14
AMC Concord DL,1,0.02,0.98
AMC Concord,0,0.79,0.21
AMC Concord,1,0.06,0.94
AMC Gremlin,0,0.92,0.08
AMC Gremlin,0,0.74,0.26

In [44]:
#ca1 = ca.drop(['name', 'predict'], axis=1)
ca1=ca
ca1

name,predict,p0,p1
AMC Ambassador Brougham,0,1,0
AMC Ambassador DPL,0,1,0
AMC Ambassador SST,0,0.98,0.02
AMC Concord DL 6,0,0.67,0.33
AMC Concord DL,0,0.86,0.14
AMC Concord DL,1,0.02,0.98
AMC Concord,0,0.79,0.21
AMC Concord,1,0.06,0.94
AMC Gremlin,0,0.92,0.08
AMC Gremlin,0,0.74,0.26

In [45]:
n = len(ca1['po'])
n

406

In [46]:
import numpy as np
ca2=ca1.sort(by = 'p0')
ca2['decile']=np.NaN
ca2['decile_rank']=np.NaN

In [47]:
import math

l=[]
def quant():
    
    for i in range(1,11):
        d= (i*(n+1))/11
        x = ca2[math.floor(d),'p0']   
        y= ca2[math.ceil(d),'p0'] 
        yy= x+round(d%int(d),2)*(y-x) 
        l.append(yy)

quant()
l

[0.0, 0.0, 0.0, 0.0, 0.04, 0.16, 0.78, 0.96, 1.0, 1.0]

In [49]:

num = math.floor(n/10)
print("num",num)  


x1=0
print("x1",x1)

for i in range(1,11):

    x2 = i *(math.floor(num))
   

    ca2[x1:x2,'decile']=l[i-1]
    ca2[x1:x2,'decile_rank']=i
    x1= i *(math.floor(num))+1
    print("x1",x1)
ca2

num 40
x1 0
x1 41
x1 81
x1 121
x1 161
x1 201
x1 241
x1 281
x1 321
x1 361
x1 401

name,predict,p0,p1,decile,decile_rank
AMC Spirit DL,1,0,1,0,1
Audi 100 LS,1,0,1,0,1
Audi 100 LS,1,0,1,0,1
Audi 4000,1,0,1,0,1
Audi 5000,1,0,1,0,1
BMW 320i,1,0,1,0,1
Buick Opel Isuzu Deluxe,1,0,1,0,1
Buick Skylark Limited,1,0,1,0,1
Buick Skylark,1,0,1,0,1
Chevrolet Camaro,1,0,1,0,1

In [50]:
ca2.head(400)

name,predict,p0,p1,decile,decile_rank
AMC Spirit DL,1,0,1,0,1
Audi 100 LS,1,0,1,0,1
Audi 100 LS,1,0,1,0,1
Audi 4000,1,0,1,0,1
Audi 5000,1,0,1,0,1
BMW 320i,1,0,1,0,1
Buick Opel Isuzu Deluxe,1,0,1,0,1
Buick Skylark Limited,1,0,1,0,1
Buick Skylark,1,0,1,0,1
Chevrolet Camaro,1,0,1,0,1
Chevrolet Cavalier 2-Door,1,0,1,0,1
Chevrolet Chevette,1,0,1,0,1
Chevrolet Chevette,1,0,1,0,1
Chevrolet Chevette,1,0,1,0,1
Chevrolet Chevette,1,0,1,0,1
Chevrolet Citation,1,0,1,0,1
Chevrolet Citation,1,0,1,0,1
Chevrolet Citation,1,0,1,0,1
Chevrolet Vega,1,0,1,0,1
Chevrolet Woody,1,0,1,0,1
Chrysler Lebaron Medallion,1,0,1,0,1
Datsun 200SX,1,0,1,0,1
Datsun 210,1,0,1,0,1
Datsun 210,1,0,1,0,1
Datsun 210,1,0,1,0,1
Datsun 310 GX,1,0,1,0,1
Datsun 310,1,0,1,0,1
Datsun 510 Hatchback,1,0,1,0,1
Datsun 510,1,0,1,0,1
Datsun 610,1,0,1,0,1
Datsun 710,1,0,1,0,1
Datsun 710,1,0,1,0,1
Datsun B-210,1,0,1,0,1
Datsun B210 GX,1,0,1,0,1
Datsun B210,1,0,1,0,1
Datsun F-10 Hatchback,1,0,1,0,1
Datsun PL510,1,0,1,0,1
Datsun PL510,1,0,1,0,1
Dodge Aries SE,1,0,1,0,1
Dodge Aries Wagon (Wagon),1,0,1,0,1
Dodge Charger 2.2,1,0,1,nan,nan
Dodge Colt (Wagon),1,0,1,0,2
Dodge Colt Hardtop,1,0,1,0,2
Dodge Colt Hatchback Custom,1,0,1,0,2
Dodge Colt M/M,1,0,1,0,2
Dodge Colt,1,0,1,0,2
Dodge Colt,1,0,1,0,2
Dodge Omni,1,0,1,0,2
Fiat 124 TC,1,0,1,0,2
Fiat 124B,1,0,1,0,2
Fiat 128,1,0,1,0,2
Fiat 131,1,0,1,0,2
Fiat Strada Custom,1,0,1,0,2
Fiat X1.9,1,0,1,0,2
Ford Capri II,1,0,1,0,2
Ford Escort 2H,1,0,1,0,2
Ford Escort 4W,1,0,1,0,2
Ford Fairmont (Man),1,0,1,0,2
Ford Fairmont 4,1,0,1,0,2
Ford Fairmont Futura,1,0,1,0,2
Ford Fiesta,1,0,1,0,2
Ford Mustang Cobra,1,0,1,0,2
Ford Mustang GL,1,0,1,0,2
Ford Mustang II 2+2,1,0,1,0,2
Ford Pinto (Wagon),1,0,1,0,2
Ford Pinto,1,0,1,0,2
Ford Pinto,1,0,1,0,2
Ford Pinto,1,0,1,0,2
Ford Ranger,1,0,1,0,2
Honda Accord CVCC,1,0,1,0,2
Honda Accord LX,1,0,1,0,2
Honda Accord,1,0,1,0,2
Honda Accord,1,0,1,0,2
Honda Civic (Auto),1,0,1,0,2
Honda Civic 1300,1,0,1,0,2
Honda Civic 1500 GL,1,0,1,0,2
Honda Civic CVCC,1,0,1,0,2
Honda Civic CVCC,1,0,1,0,2
Honda Civic,1,0,1,0,2
Honda Civic,1,0,1,0,2
Honda Civic,1,0,1,nan,nan
Honda Prelude,1,0,1,0,3
Maxda GLC Deluxe,1,0,1,0,3
Mazda 626,1,0,1,0,3
Mazda 626,1,0,1,0,3
Mazda GLC 4,1,0,1,0,3
Mazda GLC Custom L,1,0,1,0,3
Mazda GLC Custom,1,0,1,0,3
Mazda GLC Deluxe,1,0,1,0,3
Mazda GLC,1,0,1,0,3
Mercury Lynx L,1,0,1,0,3
Nissan Stanza XE,1,0,1,0,3
Oldsmobile Omega Brougham,1,0,1,0,3
Oldsmobile Starfire SX,1,0,1,0,3
Opel 1900,1,0,1,0,3
Opel Manta,1,0,1,0,3
Peugeot 304,1,0,1,0,3
Peugeot 504,1,0,1,0,3
Plymouth Arrow GS,1,0,1,0,3
Plymouth Champ,1,0,1,0,3
Plymouth Cricket,1,0,1,0,3
Plymouth Horizon 4,1,0,1,0,3
Plymouth Horizon Miser,1,0,1,0,3
Plymouth Horizon TC3,1,0,1,0,3
Plymouth Reliant,1,0,1,0,3
Plymouth Reliant,1,0,1,0,3
Plymouth Sapporo,1,0,1,0,3
Pontiac J2000 Se Hatchback,1,0,1,0,3
Pontiac Phoenix,1,0,1,0,3
Pontiac Phoenix,1,0,1,0,3
Pontiac Sunbird Coupe,1,0,1,0,3
Renault 12 (Wagon),1,0,1,0,3
Renault 12TL,1,0,1,0,3
Renault 18I,1,0,1,0,3
Renault 5 Gtl,1,0,1,0,3
Renault Lecar Deluxe,1,0,1,0,3
Saab 99E,1,0,1,0,3
Subaru DL,1,0,1,0,3
Subaru DL,1,0,1,0,3
Subaru,1,0,1,0,3
Toyota Celica GT Liftback,1,0,1,nan,nan
Toyota Celica GT,1,0,1,0,4
Toyota Corolla Liftback,1,0,1,0,4
Toyota Corolla Tercel,1,0,1,0,4
Toyota Corolla,1,0,1,0,4
Toyota Corolla,1,0,1,0,4
Toyota Corolla,1,0,1,0,4
Toyota Corolla,1,0,1,0,4
Toyota Corolla,1,0,1,0,4
Toyota Corona Hardtop,1,0,1,0,4
Toyota Corona Liftback,1,0,1,0,4
Toyota Corona,1,0,1,0,4
Toyota Corona,1,0,1,0,4
Toyota Corona,1,0,1,0,4
Toyota Cressida,1,0,1,0,4
Toyota Starlet,1,0,1,0,4
Toyota Tercel,1,0,1,0,4
Triumph TR7 Coupe,1,0,1,0,4
Vokswagen Rabbit,1,0,1,0,4
Volkswagen 1131 Deluxe Sedan,1,0,1,0,4
Volkswagen Dasher (Diesel),1,0,1,0,4
Volkswagen Dasher,1,0,1,0,4
Volkswagen Dasher,1,0,1,0,4
Volkswagen Dasher,1,0,1,0,4
Volkswagen Jetta,1,0,1,0,4
Volkswagen Model 111,1,0,1,0,4
Volkswagen Pickup,1,0,1,0,4
Volkswagen Rabbit C (Diesel),1,0,1,0,4
Volkswagen Rabbit Custom Diesel,1,0,1,0,4
Volkswagen Rabbit Custom,1,0,1,0,4
Volkswagen Rabbit Custom,1,0,1,0,4
Volkswagen Rabbit L,1,0,1,0,4
Volkswagen Rabbit,1,0,1,0,4
Volkswagen Rabbit,1,0,1,0,4
Volkswagen Rabbit,1,0,1,0,4
Volkswagen Scirocco,1,0,1,0,4
Volkswagen Super Beetle 117,1,0,1,0,4
Volkswagen Type 3,1,0,1,0,4
Toyouta Corona Mark II (Wagon),1,0.01,0.99,0,4
AMC Concord DL,1,0.02,0.98,0,4
Audi 100 LS,1,0.02,0.98,nan,nan
Audi 5000S (Diesel),1,0.02,0.98,0.04,5
Audi Fox,1,0.02,0.98,0.04,5
Chevrolet Vega (Wagon),1,0.02,0.98,0.04,5
Chevrolet Vega 2300,1,0.02,0.98,0.04,5
Chevy S-10,1,0.02,0.98,0.04,5
Datsun 200SX,1,0.02,0.98,0.04,5
Datsun 510 (Wagon),1,0.02,0.98,0.04,5
Datsun 810,1,0.02,0.98,0.04,5
Dodge Rampage,1,0.02,0.98,0.04,5
Ford Fairmont,1,0.02,0.98,0.04,5
Ford Pinto Runabout,1,0.02,0.98,0.04,5
Ford Pinto,1,0.02,0.98,0.04,5
Mercury Capri 2000,1,0.02,0.98,0.04,5
Opel 1900,1,0.02,0.98,0.04,5
Plymouth Horizon,1,0.02,0.98,0.04,5
Subaru,1,0.02,0.98,0.04,5
Toyota Corolla 1600 (Wagon),1,0.02,0.98,0.04,5
Toyota Corona Mark II,1,0.02,0.98,0.04,5
Toyota Corona,1,0.02,0.98,0.04,5
Volkswagen 411 (Wagon),1,0.02,0.98,0.04,5
Volkswagen Rabbit,1,0.02,0.98,0.04,5
AMC Gremlin,1,0.04,0.96,0.04,5
Datsun 810 Maxima,1,0.04,0.96,0.04,5
Dodge Colt,1,0.04,0.96,0.04,5
Ford Maverick,1,0.04,0.96,0.04,5
Opel Manta,1,0.04,0.96,0.04,5
Peugeot 504,1,0.04,0.96,0.04,5
Peugeot 504,1,0.04,0.96,0.04,5
Peugeot 505S Turbo Diesel,1,0.04,0.96,0.04,5
Plymouth Duster,1,0.04,0.96,0.04,5
Pontiac Astro,1,0.04,0.96,0.04,5
AMC Concord,1,0.06,0.94,0.04,5
Buick Century Limited,1,0.06,0.94,0.04,5
Chevrolet Cavalier,1,0.06,0.94,0.04,5
Datsun 1200,1,0.06,0.94,0.04,5
Ford Maverick,1,0.06,0.94,0.04,5
Mazda RX-4,1,0.06,0.94,0.04,5
Mercury Capri V6,1,0.06,0.94,0.04,5
Saab 900S,1,0.06,0.94,0.04,5
Saab 99LE,1,0.06,0.94,nan,nan
Volkswagen Super Beetle,1,0.06,0.94,0.16,6
Chevrolet Cavalier Wagon,1,0.08,0.92,0.16,6
Chevrolet Vega,1,0.08,0.92,0.16,6
Mercedes-Benz 240D,1,0.08,0.92,0.16,6
Saab 99GLE,1,0.08,0.92,0.16,6
Volvo Diesel,1,0.08,0.92,0.16,6
Ford Fairmont (Auto),1,0.09,0.91,0.16,6
Plymouth Duster,1,0.09,0.91,0.16,6
Buick Century,1,0.1,0.9,0.16,6
Fiat 124 Sport Coupe,1,0.1,0.9,0.16,6
Toyota Corolla 1200,1,0.1,0.9,0.16,6
Volvo 244DL,1,0.1,0.9,0.16,6
Ford Granada GL,1,0.12,0.88,0.16,6
Ford Pinto,1,0.12,0.88,0.16,6
Pontiac Lemans V6,1,0.12,0.88,0.16,6
Ford Maverick,1,0.13,0.87,0.16,6
Dodge Aspen 6,1,0.14,0.86,0.16,6
Ford Granada L,1,0.14,0.86,0.16,6
Oldsmobile Cutlass Ciera (Diesel),1,0.14,0.86,0.16,6
Saab 99LE,1,0.14,0.86,0.16,6
Toyota Corolla 1200,1,0.14,0.86,0.16,6
BMW 2002,1,0.16,0.84,0.16,6
Mercury Zephyr,1,0.16,0.84,0.16,6
Mazda RX-7 Gs,1,0.18,0.82,0.16,6
Toyota Mark II,1,0.18,0.82,0.16,6
Buick Century Special,1,0.19,0.81,0.16,6
Datsun 280ZX,1,0.2,0.8,0.16,6
Mercedes-Benz 300D,1,0.2,0.8,0.16,6
Buick Skylark,1,0.24,0.76,0.16,6
Chevrolet Malibu,1,0.24,0.76,0.16,6
Buick Skyhawk,1,0.26,0.74,0.16,6
Plymouth Valiant,1,0.26,0.74,0.16,6
Oldsmobile Cutlass Salon Brougham,1,0.27,0.73,0.16,6
Plymouth Volare,1,0.27,0.73,0.16,6
AMC Hornet,1,0.28,0.72,0.16,6
Oldsmobile Cutlass LS,1,0.3,0.7,0.16,6
Chevrolet Nova,1,0.32,0.68,0.16,6
Mercury Monarch Ghia,1,0.36,0.64,0.16,6
Fiat 128,1,0.38,0.62,0.16,6
Chevrolet Vega,0,0.42,0.58,nan,nan
Volvo 144EA,0,0.44,0.56,0.78,7
Peugeot 504 (Wagon),0,0.5,0.5,0.78,7
Mercury Zephyr 6,0,0.53,0.47,0.78,7
Volvo 264GL,0,0.56,0.44,0.78,7
AMC Hornet,0,0.57,0.43,0.78,7
Volvo 245,0,0.62,0.38,0.78,7
Toyota Carina,0,0.66,0.34,0.78,7
AMC Concord DL 6,0,0.67,0.33,0.78,7
Toyota Mark II,0,0.68,0.32,0.78,7
Ford Pinto,0,0.7,0.3,0.78,7
Volvo 145E (Wagon),0,0.7,0.3,0.78,7
Plymouth Valiant,0,0.72,0.28,0.78,7
AMC Gremlin,0,0.74,0.26,0.78,7
Citroen DS-21 Pallas,0,0.74,0.26,0.78,7
Mercedes-Benz 280S,0,0.74,0.26,0.78,7
Ford Granada Ghia,0,0.76,0.24,0.78,7
Chevrolet Monte Carlo Landau,0,0.78,0.22,0.78,7
Peugeot 504,0,0.78,0.22,0.78,7
Plymouth Duster,0,0.78,0.22,0.78,7
AMC Concord,0,0.79,0.21,0.78,7
Ford Futura,0,0.8,0.2,0.78,7
Dodge Aspen,0,0.82,0.18,0.78,7
Oldsmobile Cutlass Salon Brougham,0,0.82,0.18,0.78,7
Peugeot 604SL,0,0.83,0.17,0.78,7
Chrysler Lebaron Salon,0,0.84,0.16,0.78,7
Ford Maverick,0,0.84,0.16,0.78,7
Mazda RX-2 Coupe,0,0.85,0.15,0.78,7
AMC Concord DL,0,0.86,0.14,0.78,7
Maxda RX-3,0,0.86,0.14,0.78,7
Buick Regal Sport Coupe (Turbo),0,0.88,0.12,0.78,7
Pontiac Phoenix LJ,0,0.88,0.12,0.78,7
AMC Pacer D/L,0,0.9,0.1,0.78,7
Ford Torino,0,0.9,0.1,0.78,7
Mercury Monarch,0,0.9,0.1,0.78,7
AMC Gremlin,0,0.92,0.08,0.78,7
Chevrolet Monza 2+2,0,0.92,0.08,0.78,7
Plymouth Valiant Custom,0,0.92,0.08,0.78,7
Chevrolet Malibu Classic (Wagon),0,0.94,0.06,0.78,7
Ford LTD Landau,0,0.94,0.06,0.78,7
Ford Maverick,0,0.94,0.06,nan,nan
Ford Mustang,0,0.94,0.06,0.96,8
Plymouth Satellite Custom,0,0.94,0.06,0.96,8
Dodge Diplomat,0,0.95,0.05,0.96,8
AMC Hornet,0,0.96,0.04,0.96,8
AMC Hornet,0,0.96,0.04,0.96,8
AMC Matador,0,0.96,0.04,0.96,8
AMC Matador,0,0.96,0.04,0.96,8
Buick Century,0,0.96,0.04,0.96,8
Chevrolet Nova,0,0.96,0.04,0.96,8
Dodge Aspen,0,0.96,0.04,0.96,8
Dodge Challenger SE,0,0.96,0.04,0.96,8
Ford Granada,0,0.96,0.04,0.96,8
Ford Mustang Boss 302,0,0.96,0.04,0.96,8
Mercury Grand Marquis,0,0.96,0.04,0.96,8
Plymouth Volare Custom,0,0.96,0.04,0.96,8
Pontiac Ventura Sj,0,0.96,0.04,0.96,8
AMC Ambassador SST,0,0.98,0.02,0.96,8
AMC Gremlin,0,0.98,0.02,0.96,8
AMC Hornet Sportabout (Wagon),0,0.98,0.02,0.96,8
AMC Matador,0,0.98,0.02,0.96,8
Cadillac Eldorado,0,0.98,0.02,0.96,8
Chevrolet Chevelle Malibu,0,0.98,0.02,0.96,8
Chevrolet Concours,0,0.98,0.02,0.96,8
Chevrolet Nova Custom,0,0.98,0.02,0.96,8
Chevrolet Nova,0,0.98,0.02,0.96,8
Chrysler Lebaron Town & Country (Wagon),0,0.98,0.02,0.96,8
Dodge Aspen SE,0,0.98,0.02,0.96,8
Dodge D100,0,0.98,0.02,0.96,8
Dodge Dart Custom,0,0.98,0.02,0.96,8
Dodge St. Regis,0,0.98,0.02,0.96,8
Ford Gran Torino,0,0.98,0.02,0.96,8
Ford Mustang II,0,0.98,0.02,0.96,8
Oldsmobile Cutlass Supreme,0,0.98,0.02,0.96,8
Plymouth Fury,0,0.98,0.02,0.96,8
Pontiac Firebird,0,0.98,0.02,0.96,8
Chevrolet Chevelle Malibu Classic,0,0.99,0.01,0.96,8
AMC Ambassador Brougham,0,1,0,0.96,8
AMC Ambassador DPL,0,1,0,0.96,8
AMC Matador (Wagon),0,1,0,0.96,8
AMC Matador (Wagon),0,1,0,nan,nan
AMC Matador,0,1,0,1,9
AMC Matador,0,1,0,1,9
AMC Pacer,0,1,0,1,9
AMC Rebel SST (Wagon),0,1,0,1,9
AMC Rebel SST,0,1,0,1,9
Buick Century 350,0,1,0,1,9
Buick Century Luxus (Wagon),0,1,0,1,9
Buick Electra 225 Custom,0,1,0,1,9
Buick Estate Wagon (Wagon),0,1,0,1,9
Buick Estate Wagon (Wagon),0,1,0,1,9
Buick Lesabre Custom,0,1,0,1,9
Buick Skylark 320,0,1,0,1,9
Cadillac Seville,0,1,0,1,9
Chevroelt Chevelle Malibu,0,1,0,1,9
Chevrolet Bel Air,0,1,0,1,9
Chevrolet Caprice Classic,0,1,0,1,9
Chevrolet Caprice Classic,0,1,0,1,9
Chevrolet Caprice Classic,0,1,0,1,9
Chevrolet Chevelle Concours (Wagon),0,1,0,1,9
Chevrolet Chevelle Concours (Wagon),0,1,0,1,9
Chevrolet Chevelle Malibu Classic,0,1,0,1,9
Chevrolet Chevelle Malibu,0,1,0,1,9
Chevrolet Impala,0,1,0,1,9
Chevrolet Impala,0,1,0,1,9
Chevrolet Impala,0,1,0,1,9
Chevrolet Impala,0,1,0,1,9
Chevrolet Malibu,0,1,0,1,9
Chevrolet Monte Carlo Landau,0,1,0,1,9
Chevrolet Monte Carlo S,0,1,0,1,9
Chevrolet Monte Carlo,0,1,0,1,9
Chevy C10,0,1,0,1,9
Chevy C20,0,1,0,1,9
Chrysler Cordoba,0,1,0,1,9
Chrysler New Yorker Brougham,0,1,0,1,9
Chrysler Newport Royal,0,1,0,1,9
Dodge Coronet Brougham,0,1,0,1,9
Dodge Coronet Custom (Wagon),0,1,0,1,9
Dodge Coronet Custom,0,1,0,1,9
Dodge D200,0,1,0,1,9
Dodge Magnum XE,0,1,0,nan,nan
Dodge Monaco (Wagon),0,1,0,1,10
Dodge Monaco Brougham,0,1,0,1,10
Ford Country Squire (Wagon),0,1,0,1,10
Ford Country Squire (Wagon),0,1,0,1,10
Ford Country,0,1,0,1,10
Ford F108,0,1,0,1,10
Ford F250,0,1,0,1,10
Ford Galaxie 500,0,1,0,1,10
Ford Galaxie 500,0,1,0,1,10
Ford Galaxie 500,0,1,0,1,10
Ford Gran Torino (Wagon),0,1,0,1,10
Ford Gran Torino (Wagon),0,1,0,1,10
Ford Gran Torino,0,1,0,1,10
Ford Gran Torino,0,1,0,1,10
Ford LTD,0,1,0,1,10
Ford LTD,0,1,0,1,10
Ford Thunderbird,0,1,0,1,10
Ford Torino (Wagon),0,1,0,1,10
Ford Torino 500,0,1,0,1,10
Hi 1200D,0,1,0,1,10
Mercury Cougar Brougham,0,1,0,1,10
Mercury Marquis Brougham,0,1,0,1,10
Mercury Marquis,0,1,0,1,10
Oldsmobile Delta 88 Royale,0,1,0,1,10
Oldsmobile Omega,0,1,0,1,10
Oldsmobile Vista Cruiser,0,1,0,1,10
Plymouth Barracuda 340,0,1,0,1,10
Plymouth Custom Suburb,0,1,0,1,10
Plymouth Fury Gran Sedan,0,1,0,1,10
Plymouth Fury III,0,1,0,1,10
Plymouth Fury III,0,1,0,1,10
Plymouth Fury III,0,1,0,1,10
Plymouth Grand Fury,0,1,0,1,10
Plymouth Satellite (Wagon),0,1,0,1,10
Plymouth Satellite Custom (Wagon),0,1,0,1,10
Plymouth Satellite Sebring,0,1,0,1,10
Plymouth Satellite,0,1,0,1,10
Plymouth Volare Premier V8,0,1,0,1,10
Pontiac Catalina Brougham,0,1,0,1,10